{{- $gw := .Values.istio.gateway }}
{{- if and .Values.enabled $gw.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ $gw.name }}
  namespace: {{ $gw.namespace | default "istio-system" }}
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
spec:
  selector:
    {{- if $gw.selector }}
    {{- toYaml $gw.selector | nindent 4 }}
    {{- else }}
    istio: ingressgateway
    {{- end }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range $gw.hosts }}
    - {{ . | quote }}
    {{- end }}
  {{- if $gw.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: {{ $gw.tls.mode }}
      credentialName: {{ $gw.tls.credentialName }}
    hosts:
    {{- range $gw.hosts }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
{{- end }}
