{{- if and .Values.istio.enabled .Values.istio.mtls.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
---
{{- if .Values.istio.database.postgres.disableMtls }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: postgres-disable-mtls
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: postgres
  mtls:
    mode: DISABLE
{{- end }}
---
{{- if .Values.istio.database.redis.disableMtls }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: redis-disable-mtls
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: redis
  mtls:
    mode: DISABLE
{{- end }}
---
# 모니터링 서비스 - Kiali/Jaeger (istio-system, sidecar 없음)에서 접근 가능하도록 PERMISSIVE 모드 적용
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: prometheus-permissive-mtls
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: prometheus
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: grafana-permissive-mtls
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: grafana
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: loki-permissive-mtls
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: loki
  mtls:
    mode: PERMISSIVE
{{- end }}
