apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: wealist-prod
  source:
    repoURL: https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-prod
    path: k8s/helm/charts/auth-service
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/base.yaml
        - ../../environments/prod.yaml
      parameters:
        - name: image.repository
          value: "auth-service"
        - name: image.tag
          value: "prod-latest"
        - name: externalSecrets.enabled
          value: "true"
        - name: config.SPRING_DATA_REDIS_SSL_ENABLED
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
