apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-monitoring-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"  # Istio 설정 이후에 설치
spec:
  project: wealist-prod
  source:
    repoURL: https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-prod
    path: k8s/helm/charts/wealist-monitoring
    helm:
      valueFiles:
        - ../../environments/base.yaml
        - ../../environments/prod.yaml
      parameters:
        - name: global.namespace
          value: wealist-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true