apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-service-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: wealist-staging
  source:
    repoURL: https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-staging
    path: k8s/helm/charts/chat-service
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/base.yaml
        - ../../environments/staging.yaml
      parameters:
        - name: global.imageRegistry
          value: "290008131187.dkr.ecr.ap-northeast-2.amazonaws.com"
        - name: image.repository
          value: "chat-service"
        - name: image.tag
          value: "dev-latest"
        - name: imagePullSecrets[0].name
          value: "ecr-secret"
        - name: shared.config.DB_HOST
          value: "host.docker.internal"
        - name: shared.config.POSTGRES_HOST
          value: "host.docker.internal"
        - name: shared.config.REDIS_HOST
          value: "host.docker.internal"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
