apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-monitoring-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"  # Istio 설정 이후에 설치
spec:
  project: wealist-staging
  source:
    repoURL: https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-staging
    path: k8s/helm/charts/wealist-monitoring
    helm:
      valueFiles:
        - ../../environments/base.yaml
        - ../../environments/staging.yaml
        # - ../../environments/dev-secrets.yaml
      parameters:
        - name: global.namespace
          value: wealist-staging
        - name: postgresExporter.config.host
          value: postgres
        - name: redisExporter.config.host
          value: redis
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true