# k8s/argocd/apps/staging/project.yaml
# Staging 환경용 AppProject
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wealist-staging
  namespace: argocd
spec:
  description: Wealist Staging Environment
  sourceRepos:
    - "https://github.com/OrangesCloud/wealist-project-advanced-k8s.git"
  destinations:
    - namespace: wealist-staging
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"