apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-apps-staging
  namespace: argocd
spec:
  project: wealist-staging
  source:
    repoURL: https://github.com/212clab/wealist-project-advanced-k8s-forked.git
    targetRevision: argo-develop
    path: k8s/argocd/apps/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
