apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-apps-staging
  namespace: argocd
spec:
  project: wealist-staging
  source:
    repoURL: https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-staging
    path: k8s/argocd/apps/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
