apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-service-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: wealist-staging
  source:
    repoURL: https://github.com/212clab/wealist-project-advanced-k8s-forked.git
    targetRevision: argo-develop
    path: k8s/helm/charts/storage-service
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/base.yaml
        - ../../environments/staging.yaml
      parameters:
        - name: global.imageRegistry
          value: "290008131187.dkr.ecr.ap-northeast-2.amazonaws.com"
        - name: image.repository
          value: "storage-service"
        - name: image.tag
          value: "dev-latest"
        - name: imagePullSecrets[0].name
          value: "ecr-secret"
        - name: shared.config.DB_HOST
          value: "172.17.0.1"
        - name: shared.config.POSTGRES_HOST
          value: "172.17.0.1"
        - name: shared.config.REDIS_HOST
          value: "172.17.0.1"
        - name: config.DB_NAME
          value: "wealist"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
