apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noti-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: wealist
  source:
    repoURL: https://github.com/OrangesCloud/wealist-argo-helm.git 
    targetRevision: dev
    path: k8s/helm/charts/noti-service
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/dev.yaml
      parameters:
        - name: image.tag
          value: "latest"
        - name: global.imageRegistry
          value: "localhost:5001"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev  # 여기 수정 다른 브런치면
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
