apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: wealist
  source:
    repoURL:  https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-dev
    path: k8s/helm/charts/user-service
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/base.yaml
        - ../../environments/dev.yaml
      parameters:
        - name: image.tag
          value: "service-deploy-dev-79620c2"  # ← CI가 여기 업데이트
        - name: image.repository
          value: "ghcr.io/orangescloud/user-service"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
