apiVersion: v2
name: frontend
description: weAlist Frontend (React + Vite)
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: weAlist Team
    email: team@wealist.io
dependencies:
  - name: wealist-common
    version: "1.0.0"
    repository: "file://../wealist-common"
