apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-service-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notifications.argoproj.io/subscribe.on-deployed.webhook: discord
    notifications.argoproj.io/subscribe.on-sync-failed.webhook: discord
    notifications.argoproj.io/subscribe.on-health-degraded.webhook: discord
spec:
  project: wealist-dev
  source:
    repoURL: https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-dev
    path: k8s/helm/charts/chat-service
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/base.yaml
        - ../../environments/dev.yaml
      parameters:
        - name: global.imageRegistry
          value: "290008131187.dkr.ecr.ap-northeast-2.amazonaws.com"
        - name: image.repository
          value: "chat-service"
        - name: image.tag
          value: "56-4ff1148"
        - name: imagePullSecrets[0].name
          value: "ecr-secret"
        - name: shared.config.DB_HOST
          value: "postgres"
        - name: shared.config.POSTGRES_HOST
          value: "postgres"
        - name: shared.config.REDIS_HOST
          value: "redis"
        - name: config.DB_NAME
          value: "wealist"
        - name: config.DB_USER
          value: "wealist"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
