apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-istio-config-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # 서비스들 이후에 설치
    notifications.argoproj.io/subscribe.on-deployed.webhook: discord
    notifications.argoproj.io/subscribe.on-sync-failed.webhook: discord
    notifications.argoproj.io/subscribe.on-health-degraded.webhook: discord
spec:
  project: wealist-dev
  source:
    repoURL: https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-dev
    path: k8s/helm/charts/istio-config
    helm:
      valueFiles:
        - ../../environments/base.yaml
        - ../../environments/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev
  # Argo Rollouts가 VirtualService의 weight를 수정할 때 OutOfSync 방지
  ignoreDifferences:
    - group: networking.istio.io
      kind: VirtualService
      jqPathExpressions:
        - .spec.http[].route[].weight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true