apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-monitoring-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12" # Istio 설정 이후에 설치
    notifications.argoproj.io/subscribe.on-deployed.webhook: discord
    notifications.argoproj.io/subscribe.on-sync-failed.webhook: discord
    notifications.argoproj.io/subscribe.on-health-degraded.webhook: discord
spec:
  project: wealist-dev
  source:
    repoURL: https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-dev
    path: k8s/helm/charts/wealist-monitoring
    helm:
      valueFiles:
        - ../../environments/base.yaml
        - ../../environments/dev.yaml
      parameters:
        - name: global.namespace
          value: wealist-dev
        # In-cluster DB (postgres/redis Service)
        - name: postgresExporter.config.host
          value: "postgres"
        - name: redisExporter.config.host
          value: "redis"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
