# k8s/argocd/apps/dev/project.yaml
# Dev 환경용 AppProject
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wealist-dev
  namespace: argocd
spec:
  description: Wealist Dev Environment
  sourceRepos:
    - "https://github.com/OrangesCloud/wealist-project-advanced-k8s.git"
    - "https://github.com/OrangesCloud/wealist-project-advanced-k8s.git"
  destinations:
    - namespace: wealist-dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: istio-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "external-secrets.io"
      kind: ClusterSecretStore
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"