# Auth Service Secret
# cp secret.yaml.example secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  JWT_SECRET: "local-dev-jwt-secret-key-must-be-at-least-64-characters-long-for-hs512-algorithm"
  GOOGLE_CLIENT_ID: "640996696843-gtht74dpnn9c4u7mb6k5craur1vojgbk.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
