apiVersion: v2
name: wealist-infrastructure
description: weAlist Infrastructure (PostgreSQL, Redis, MinIO, Monitoring)
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: weAlist Team
    email: team@wealist.io
