{{- if .Values.alloy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: {{ .Values.global.namespace }}
  labels:
    app: alloy
    app.kubernetes.io/name: alloy
    app.kubernetes.io/component: log-collector
{{- end }}
