{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: {{ .Values.global.namespace }}
  labels:
    app: tempo
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: tracing
{{- end }}
